language: rust

sudo: false
matrix:
  include:
    - os: linux
      rust: nightly
      env:
        - FORMAT=1
        - BENCH=1
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
        - travis_wait 30 cargo install -f rustfmt
      after_success:
        - travis-cargo doc-upload
    - os: osx
      rust: nightly
script:
  - if [ "$FORMAT" = "1" ]; then cargo fmt -- --write-mode=diff; fi
  - cargo build
  - cargo test
  - rustdoc --test README.md -L target/debug -L target/debug/deps
  - cargo doc --no-deps
  - if [ "$BENCH" = "1" ]; then cargo bench; fi
env:
  global:
    - secure: xDlMeNL9ET86NfvWuP9sckf3Ghz31/v9Cpk7ScF2jf1tsk9GHTcqGF86BQV7zSaPc2S4aI3FrpiyuMrOfPV0Cr8BJvPwR9KdBmgNkcu4SclwjzWlVPMvSKMywPdLWV+W9Gz+OsWLEqpt/pLzCCBP4VaqzvaG8s4qb9zjiletlEdnIjgmhblZw3wMueTNRxS55uSlOuT7f2BWIIGK+kpgouHFr4f7LSoFsYdQxA5pb4Khh8fGadWdsQBJ3N9Ngshpc4YiBHmYaGNDNC635hrLWQAjpmmJWmX/msOnBsPynnxJN5K+aEQLRLK/W0IYbrtIzz4x53zFWhUf+q8jR7h/pLELpS2Guz7fEuXVBNby19Iv5M/Vv6k4pD0OFhB+JiUsC5qZbHJFOBG/9sFr2AuHEHWe0JIGQBrLytxg3t1st1OOaPgGjZEft8YRKqv72NL8c7K9W9V274MGwfytRR1QFKf8vAjg6aIWpnCDgpuiFETySDYPI9mZ0VZ0LunYcpaqnJmjGqYXZkYBpbse5JaU9UteaqsACsCpLupurs5EZlK3tm6NlyParR+tGQZNtWDYNmqgJmtPqtJEgdbvNhP7GUtz81pN8KnydrJ98PyB8m4ihRnOfrYPgbjz8z5GmJDsCDIHx3tU8Sd8LFEKCg4svdB3oipMF/5PSa5BXv3CryQ=

notifications:
  email:
    on_success: never
